#!/usr/bin/env bash
# ComfyUI with the measured-best flags for this box.
# Generated by bench/analyse.py on 2026-08-04 08:50.
cd "$(dirname "$0")/.."
exec .venv/bin/python main.py --port "${1:-8188}" --use-sage-attention --fast
